title: Saleha Tanveer  # You can add your name here

logo: 1.png # Use a relative path to logo image 

description: I code. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: saleha.zia900@gmail.com # Allow visitors to contact you
